<?xml version="1.0" encoding="UTF-8"?>
<TestRun id="84a13b0b-f374-40f6-967a-0e23887aeca1" name="cmeyer@WV00235077 2012-03-06 18:12:13" runUser="ACTIVE\cmeyer" xmlns="http://microsoft.com/schemas/VisualStudio/TeamTest/2010">
  <TestSettings name="Local" id="c0d642b4-18b8-469e-9a2e-d44259bb5d21">
    <Description>These are default test settings for a local test run.</Description>
    <Deployment enabled="false" runDeploymentRoot="cmeyer_WV00235077 2012-03-06 18_12_13">
      <DeploymentItem filename="C:\dev\cybersource-csharp-wrapper\CybersourceAPI\bin\Debug\CybersourceAPI.dll" />
    </Deployment>
    <Execution>
      <TestTypeSpecific />
      <AgentRule name="Execution Agents">
      </AgentRule>
    </Execution>
  </TestSettings>
  <Times creation="2012-03-06T18:12:13.6043587-06:00" queuing="2012-03-06T18:12:15.9716371-06:00" start="2012-03-06T18:12:16.1776997-06:00" finish="2012-03-06T18:12:47.0177511-06:00" />
  <ResultSummary outcome="Error">
    <Counters total="1" executed="1" error="0" failed="0" timeout="0" aborted="1" inconclusive="0" passedButRunAborted="0" notRunnable="0" notExecuted="0" disconnected="0" warning="0" passed="0" completed="0" inProgress="0" pending="0" />
    <RunInfos>
      <RunInfo computerName="WV00235077" outcome="Error" timestamp="2012-03-06T18:12:47.0157979-06:00">
        <Text>Test host process exited unexpectedly.</Text>
      </RunInfo>
    </RunInfos>
  </ResultSummary>
  <TestDefinitions>
    <UnitTest name="transaction_exception_detail_get_report" storage="c:\dev\cybersource-csharp-wrapper\cybersourceapi.tests\bin\debug\cybersourceapi.tests.dll" id="f77444ee-02a7-9484-182a-574e7bfecaf5">
      <Execution id="ebe877a6-3247-4323-8eeb-6291e969ca59" />
      <TestMethod codeBase="C:/dev/cybersource-csharp-wrapper/CybersourceAPI.Tests/bin/Debug/CybersourceAPI.Tests.DLL" adapterTypeName="Microsoft.VisualStudio.TestTools.TestTypes.Unit.UnitTestAdapter, Microsoft.VisualStudio.QualityTools.Tips.UnitTest.Adapter, Version=10.0.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a" className="CybersourceAPI.Tests.Integration.TransactionExceptionDetail, CybersourceAPI.Tests, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null" name="transaction_exception_detail_get_report" />
    </UnitTest>
  </TestDefinitions>
  <TestLists>
    <TestList name="Results Not in a List" id="8c84fa94-04c1-424b-9868-57a2d4851a1d" />
    <TestList name="All Loaded Results" id="19431567-8539-422a-85d7-44ee4e166bda" />
  </TestLists>
  <TestEntries>
    <TestEntry testId="f77444ee-02a7-9484-182a-574e7bfecaf5" executionId="ebe877a6-3247-4323-8eeb-6291e969ca59" testListId="8c84fa94-04c1-424b-9868-57a2d4851a1d" />
  </TestEntries>
  <Results>
    <UnitTestResult executionId="ebe877a6-3247-4323-8eeb-6291e969ca59" testId="f77444ee-02a7-9484-182a-574e7bfecaf5" testName="transaction_exception_detail_get_report" computerName="WV00235077" duration="00:00:30.6623102" startTime="2012-03-06T18:12:16.3554409-06:00" endTime="2012-03-06T18:12:47.0177511-06:00" testType="13cdc9d9-ddb5-4fa4-a97d-d965ccfc6d4b" outcome="Aborted" testListId="8c84fa94-04c1-424b-9868-57a2d4851a1d" relativeResultsDirectory="ebe877a6-3247-4323-8eeb-6291e969ca59">
    </UnitTestResult>
  </Results>
</TestRun>